### PR TITLE
Add Pascal as a supported language

### PR DESCRIPTION
**Pull request by medovina**

### CODE REVIEW

**Comment by slgobinath** [comment]
After merging your previous PR, it has conflicts.
Could you please resolve the conflict.

Thanks

**Comment by medovina** [comment]
Merged,

**Comment by slgobinath** [comment]
Hi,
I have one more question. Did you try Pascal with Pygments? because Pascal is not listed in the available [languages list](http://pygments.org/languages/). Instead, [Delphi](https://github.com/sol/pygments/blob/master/pygments/lexers/pascal.py) is listed.

WDYT?

**Comment by medovina** [comment]
Pascal does work fine.  But now that I look at the Pygments source code, it appears that 'pascal' is just a synonym for Delphi:

https://bitbucket.org/birkenfeld/pygments-main/src/7941677dc77d4f2bf0bbd6140ade85a9454b8b80/pygments/lexers/pascal.py?at=default&fileviewer=file-view-default

So this pull request is probably unnecessary.  You could accept it if you want to allow Pascal as an alias for Delphi in libreoffice-office-highlighter, or just drop it - either is fine with me.

**Comment by slgobinath** [comment]
Hi,
We will drop this because I am not sure how it will work with other variations of Pascal.

Thanks

**Comment by medovina** [comment]
OK - fair enough.

**Pull request closed without merging**
