### PR TITLE
Bold, Italics, Background, persistent options

### PR DESCRIPTION
**Pull request by jolange**
As promised, here are some further possible improvements:

- bold and italic are handled (used by some styles, e.g.  manni)
- the background color defined by the style can be used (option in dialog)
- options in the dialog are made persistent, i.e., they are saved as a configuration setting and used when creating the dialog again, even after restarting LO
- a function has been added to repeat the highlighting with the previous settings

What do you think of these changes?

Would the last point be an option for you to replace the sub-menus? You could once choose lang=java, style=default in the dialog and after that use a keybord shortcut for `apply_previous_settings` to highlight the rest of your snippets. In that case I would again remove the language-specific functions.

### CODE REVIEW

**Comment by slgobinath** [comment]
Thank you so much @jolange 

According to my understanding, `apply_previous_settings` can be used even after restarting LO. That's awesome and +1 to remove the menu.

**Comment by jolange** [comment]
> According to my understanding, `apply_previous_settings` can be used even after restarting LO.

Yes, that's right.

> That's awesome and +1 to remove the menu.

Ok, I'll take care of that and let you know when finished!

**Comment by jolange** [comment]
@slgobinath OK, I'm done!

**Comment by jolange** [comment]
@slgobinath did you have a chance to test the changes yet?

**Comment by slgobinath** [comment]
@jolange I'm little busy. I will test and merge this PR in the coming weekend.

**Comment by jolange** [comment]
Sure, no problem, take your time!

**Comment by slgobinath** [comment]
@jolange thank you very much. It works great!

**Comment by jolange** [comment]
You're welcome!

**Pull request merged**
